# Generated by Django 4.2.13 on 2024-06-15 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_mymodel_completed_alter_mymodel_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mymodel',
            name='description',
        ),
        migrations.AlterField(
            model_name='mymodel',
            name='completed',
            field=models.BooleanField(default=True),
        ),
    ]
